### PR TITLE
[RFC 0158] Flake version 

### PR DESCRIPTION
**Pull request by lucasew**
# Summary

This RFC proposes the addition of a `version` option for `flake.nix` to define which flake spec version one flake is using, like how it's done with `docker-compose`.

This is for flake stabilization but without sacrificing future revisions.

[Rendered](https://github.com/lucasew/rfcs/blob/flake-version/rfcs/0158-flake-version.md)

### CODE REVIEW

**Comment by Ma27** [comment]
This existed in the past in form of an `edition` field, similar to the field in `Cargo.toml`. However it was removed later because parsing an edition field from a `flake.nix` means that the Nix version you're using must be able to parse the entire file. This is not the case if e.g. a very old Nix is used to read a flake.nix using newer language features (or vice versa). See also https://github.com/nixos/nix/commit/e5ea01c1a8bbd328dcc576928bf3e4271cb55399.

This RFC has the exact same issue and doesn't mention this at all.

**Comment by kevincox** [comment]
This RFC is now open for shepherd nominations.

**Comment by lucasew** [comment]
> This existed in the past in form of an `edition` field, similar to the field in `Cargo.toml`. However it was removed later because parsing an edition field from a `flake.nix` means that the Nix version you're using must be able to parse the entire file. This is not the case if e.g. a very old Nix is used to read a flake.nix using newer language features (or vice versa). See also [NixOS/nix@e5ea01c](https://github.com/NixOS/nix/commit/e5ea01c1a8bbd328dcc576928bf3e4271cb55399).
> 
> This RFC has the exact same issue and doesn't mention this at all.

I think this breakage shouldn't be so unwanted as flakes are still not marked as stable. The disruption would be much smaller if something like this would actually be introduced sooner.

It's unstable for a reason I guess

And this compatibility system can be backported to old versions if that's the case.

**Comment by Ma27** [comment]
> I think this breakage shouldn't be so unwanted as flakes are still not marked as stable. The disruption would be much smaller if something like this would actually be introduced sooner.

This is not about a break to the current flake format (I agree that it's fine especially as long as flakes are unstable to change stuff), but about future language changes that may be used in flake.nix and as a result it's not possible for older Nix versions to parse the flake.nix (and the version field inside) to find out what language level is supposed to be used.

> And this compatibility system can be backported to old versions if that's the case.

If the suggestion is about backporting new language features to older Nix versions to still be able to parse newer flake.nix files, then I'd like to hear from the Nix (and probably also Tvix) developers if they consider that feasible. I'm not too involved in either, but I highly doubt that this is sustainable and something time should be invested in.

**Comment by justinlovinger** [comment]
What about storing the version in `flake.lock`? Presumably, `flake.lock` is less likely to need future Nix features. It can be included when the lock file is generated.

If there are still concerns about `flake.lock` compatibility with Nix versions, the version could be stored in a separate plaintext file, like `.flake-version`.

Additionally, being automatically added, the version could be fully automated. Instead of manually adding a `version` field, the version can be added based on the Nix version used to run the Flake file.

**Comment by tomberek** [comment]
This RFC has not acquired enough shepherds. This typically shows lack of interest from the community. In order to progress [a full shepherd team is required](https://github.com/NixOS/rfcs/#shepherd-team). Consider trying to raise interest by [posting in Discourse](https://discourse.nixos.org/), [talking in Matrix](https://matrix.to/#/#community:nixos.org) or reaching out to people that you know.

If not enough shepherds can be found in the next month we will close this RFC until we can find enough interested participants. The PR can be reopened at any time if more shepherd nominations are made.

[See more info on the Nix RFC process here](https://github.com/NixOS/rfcs/blob/master/README.md)

**Pull request closed without merging**
