### PR TITLE
WIP: Nix-Cas rfc

### PR DESCRIPTION
**Pull request by regnat**
A draft PR to gather some preliminary reviews on this RFC before (hopefully) submitting it upstream.

This ist still quite WIP and probably needs a lot of rewriting, but the bulk of the content should be there

### CODE REVIEW

**Comment by wmertens** [comment]
Why'd you close this? It's interesting, I'm happy to see that you already have an implementation. Did you read #17 and preferably the comments? Probably we can build on your work to implement #17.

**Comment by Ericson2314** [comment]
I think they meant to submit it internally and then submit it upstream?

**Comment by regnat** [comment]
Yes sorry for that, this was supposed to be internal at that point (because a large part of it is still hypothetical from an organizational point of view). But hopefully it won't stay that way for long :)

**Comment by Ericson2314** [comment]
Good luck! I did sneak a peak and I like what I see a lot :).

**Pull request closed without merging**
