### PR TITLE
Add future work section to the template

### PR DESCRIPTION
**Pull request by shlevy**
@zimbatm @edolstra

### CODE REVIEW

**Comment by zimbatm** [comment]
@shlevy can you outline the motivation for this change?

**Comment by shlevy** [comment]
Lots of changes imply or enable future work if they happen to take full advantage (e.g. a new nix feature allows us to improve something in nixpkgs), and having some thought up front as to what those changes entail makes the scope of the change clearer, even if those future work changes aren't strictly necessary to finish the feature itself.

**Comment by zimbatm** [comment]
Would it be enough to add a related-to section where one could link and comment various items?

**Comment by shlevy** [comment]
Sure, that works fine as well.

**Comment by shlevy** [comment]
(FYI I don't have write access here)

**Comment by Profpatsch** [comment]
Sounds like a good addition; most research papers have a “Future Work” section as well.

**Pull request merged**
